flyway:
  locations: db/migration
  baseline-version: 1
  sql-migration-prefix: migration_
  baseline-on-migrate: true

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${database.url:jdbc:postgresql://localhost:5432/bot}
